[package]
name = "base58-monero"
description = "Library with support for encoding/decoding Monero base58 strings."
keywords = ["monero", "base58", "base58-check"]
version = "0.1.1"
authors = ["h4sh3d <h4sh3d@truelevel.io>"]
license-file = "LICENSE"
documentation = "https://docs.rs/base58-monero"
homepage = "https://github.com/monero-rs/base58-monero-rs"
repository = "https://github.com/monero-rs/base58-monero-rs"
readme = "README.md"

edition = "2018"

[features]
check = ["keccak-hash"]
default = ["check"]

[dependencies]
keccak-hash = { version = "0.1", optional = true }

[dev-dependencies]
hex = "0.3"
