[package]
name = "base58-monero"
description = "Library with support for encoding/decoding Monero base58 strings."
keywords = ["monero", "base58", "base58-check"]
version = "0.2.1"
authors = ["h4sh3d <h4sh3d@protonmail.com>"]
license = "MIT"
documentation = "https://docs.rs/base58-monero"
homepage = "https://github.com/monero-rs/base58-monero-rs"
repository = "https://github.com/monero-rs/base58-monero-rs"
readme = "README.md"
include = [
    "src/*",
    "README.md",
    "LICENSE",
]

edition = "2018"

[features]
check = ["tiny-keccak"]
stream = ["tokio", "async-stream", "futures-util"]
default = ["check", "stream"]

[dependencies]
tiny-keccak = { version = "2.0.1", features = ["keccak"], optional = true }
async-stream = { version = "0.2.0", optional = true }
tokio =  { version = "0.2.6", features = ["stream", "io-util"], optional = true }
futures-util = { version = "0.3.1", optional = true }
thiserror = "1.0.24"

[dev-dependencies]
hex = "0.3"
tokio =  { version = "0.2.8", features = ["full"] }

[badges]
travis-ci = { repository = "monero-rs/base58-monero-rs", branch = "master" }
